export const BALANCE = {
  EFFECTS_INITIAL_ADD_VALUE: 0,
  EFFECTS_INITIAL_MULTIPLY_VALUE: 1,

  GAME_LOOP_INTERVAL: 1000,

  HERO_REQUIRED_EXP_MULTIPLIER: 2.4,
  HERO_INITIAL_EXP_RATIO: 1,

  SPRINT_INITIAL_SIZE: 10,

  TICKET_CP_MULTIPLIER: 1.03,
  TICKET_QUEUE_INTERVAL: 15_000,

  PROJECT_INITIAL_CP: 100000,
  PROJECT_INITIAL_REWARD_MONEY_RATIO: 0.5,
};
