export const BALANCE = {
  EFFECTS_INITIAL_ADD_VALUE: 0,
  EFFECTS_INITIAL_MULTIPLY_VALUE: 1,
  GAME_LOOP_INTERVAL: 1000,

  TICKET_INITIAL_CP: 50,
  TICKET_CP_MULTIPLIER: 1.12,
  TICKET_QUEUE_INTERVAL: 3_000,

  PROJECT_INITIAL_CP: 10000,

  HERO_REQUIRED_EXP_MULTIPLIER: 2.25,
};
