export enum TicketType {
  FEATURE = 'FEATURE',
  MAINTENANCE = 'MAINTENANCE',
  BUGFIX = 'BUGFIX',
  HOTFIX = 'HOTFIX',
  TESTING = 'TESTING',
  DOCUMENTATION = 'DOCUMENTATION',
  REFACTORING = 'REFACTORING',
}
